"""Plate geometry per Bambu printer model.

GENERATED by ``scripts/generate_plate_profiles.py`` from bambulab/BambuStudio's
``resources/profiles/BBL/machine/*.json``. Do not edit by hand.

Each entry is keyed by the machine profile's ``printer_model`` and carries, in
millimetres, the values those profiles declare:

``printable_area``
    the bed polygon every extruder shares as an outer bound.
``extruder_printable_area``
    one polygon per extruder, empty for a single-extruder machine. On the H2
    series the two differ — extruder 2 cannot reach the left edge — and that gap
    is what makes a default-placed prime tower unprintable.
``bed_exclude_area``
    the front-left cutout the X1/P1 series uses to cut filament.
``printable_height``
    the Z limit, carried for completeness; the 3MF writer does not use it.

Geometry is identical across a model's nozzle variants, so the table is keyed by
model rather than by preset.
"""

from __future__ import annotations

#: ``printer_model`` -> (printable_area, extruder_printable_area, bed_exclude_area, height)
Polygon = tuple[tuple[float, float], ...]

PLATE_PROFILES: dict[str, tuple[Polygon, tuple[Polygon, ...], Polygon, float]] = {
    "Bambu Lab A1": (((0.0, 0.0), (256.0, 0.0), (256.0, 256.0), (0.0, 256.0)), (), (), 256.0),
    "Bambu Lab A1 mini": (((0.0, 0.0), (180.0, 0.0), (180.0, 180.0), (0.0, 180.0)), (), (), 180.0),
    "Bambu Lab A2L": (((0.0, 0.0), (330.0, 0.0), (330.0, 320.0), (0.0, 320.0)), (), (), 325.0),
    "Bambu Lab H2C": (
        ((0.0, 0.0), (330.0, 0.0), (330.0, 320.0), (0.0, 320.0)),
        (
            ((0.0, 0.0), (325.0, 0.0), (325.0, 320.0), (0.0, 320.0)),
            ((25.0, 0.0), (330.0, 0.0), (330.0, 320.0), (25.0, 320.0)),
        ),
        (),
        325.0,
    ),
    "Bambu Lab H2D": (
        ((0.0, 0.0), (350.0, 0.0), (350.0, 320.0), (0.0, 320.0)),
        (
            ((0.0, 0.0), (325.0, 0.0), (325.0, 320.0), (0.0, 320.0)),
            ((25.0, 0.0), (350.0, 0.0), (350.0, 320.0), (25.0, 320.0)),
        ),
        (),
        325.0,
    ),
    "Bambu Lab H2D Pro": (
        ((0.0, 0.0), (350.0, 0.0), (350.0, 320.0), (0.0, 320.0)),
        (
            ((0.0, 0.0), (325.0, 0.0), (325.0, 320.0), (0.0, 320.0)),
            ((25.0, 0.0), (350.0, 0.0), (350.0, 320.0), (25.0, 320.0)),
        ),
        (),
        325.0,
    ),
    "Bambu Lab H2S": (((0.0, 0.0), (340.0, 0.0), (340.0, 320.0), (0.0, 320.0)), (), (), 340.0),
    "Bambu Lab P1P": (
        ((0.0, 0.0), (256.0, 0.0), (256.0, 256.0), (0.0, 256.0)),
        (),
        ((0.0, 0.0), (18.0, 0.0), (18.0, 28.0), (0.0, 28.0)),
        250.0,
    ),
    "Bambu Lab P1S": (
        ((0.0, 0.0), (256.0, 0.0), (256.0, 256.0), (0.0, 256.0)),
        (),
        ((0.0, 0.0), (18.0, 0.0), (18.0, 28.0), (0.0, 28.0)),
        250.0,
    ),
    "Bambu Lab P2S": (((0.0, 0.0), (256.0, 0.0), (256.0, 256.0), (0.0, 256.0)), (), (), 256.0),
    "Bambu Lab X1": (
        ((0.0, 0.0), (256.0, 0.0), (256.0, 256.0), (0.0, 256.0)),
        (),
        ((0.0, 0.0), (18.0, 0.0), (18.0, 28.0), (0.0, 28.0)),
        250.0,
    ),
    "Bambu Lab X1 Carbon": (
        ((0.0, 0.0), (256.0, 0.0), (256.0, 256.0), (0.0, 256.0)),
        (),
        ((0.0, 0.0), (18.0, 0.0), (18.0, 28.0), (0.0, 28.0)),
        250.0,
    ),
    "Bambu Lab X1E": (
        ((0.0, 0.0), (256.0, 0.0), (256.0, 256.0), (0.0, 256.0)),
        (),
        ((0.0, 0.0), (18.0, 0.0), (18.0, 28.0), (0.0, 28.0)),
        250.0,
    ),
    "Bambu Lab X2D": (
        ((0.0, 0.0), (256.0, 0.0), (256.0, 256.0), (0.0, 256.0)),
        (
            ((0.0, 0.0), (256.0, 0.0), (256.0, 256.0), (0.0, 256.0)),
            ((20.5, 0.0), (256.0, 0.0), (256.0, 256.0), (20.5, 256.0)),
        ),
        (),
        261.0,
    ),
}

#: Short codes Bambuddy reports in ``Printer.model`` that are not the model name
#: with "Bambu Lab " removed.
EXTRA_ALIASES: dict[str, str] = {
    "A1M": "Bambu Lab A1 mini",
    "H2DP": "Bambu Lab H2D Pro",
    "X1C": "Bambu Lab X1 Carbon",
}
