"""Plate geometry per Bambu printer model.

GENERATED by ``scripts/generate_plate_profiles.py`` from bambulab/BambuStudio's
``resources/profiles/BBL/machine/*.json``. Do not edit by hand.

Each entry is keyed by the machine profile's ``printer_model`` and carries, in
millimetres, the values those profiles declare:

``printable_area``
    the bed polygon every extruder shares as an outer bound.
``extruder_printable_area``
    one polygon per extruder, empty for a single-extruder machine. On the H2
    series the two differ — extruder 2 cannot reach the left edge — and that gap
    is what makes a default-placed prime tower unprintable.
``bed_exclude_area``
    the front-left cutout the X1/P1 series uses to cut filament.
``wrapping_exclude_area``
    the strip the H2/P2S series probes for clumping ("wrapping") at the back of
    the bed. It is a no-print zone *only while* the process option
    ``enable_wrapping_detection`` is on — ``Print.cpp``'s
    ``layered_print_cleareance_valid`` then refuses a prime tower that touches it
    ("Prime Tower is too close to clumping detection area, and collisions will be
    caused") — and inert otherwise. That option lives in the process preset
    Bambuddy slices with, which ScadBuddy never sees, so the prime tower always
    avoids it (#122).
``printable_height``
    the Z limit. The 3MF writer states it in ``project_settings.config``:
    once a file claims BambuStudio identity the CLI dereferences that option
    without a null check, so it is required rather than informational (#110).
    ``extruder_printable_height`` (per extruder; the H2C's are 320 and 325) is
    deliberately not read (#122): nothing uses Z as a constraint, and the one
    consumer writes this value back under the key ``printable_height``, where
    the per-extruder minimum would misstate the profile. If Z ever becomes a
    placement constraint, read the minimum across extruders then.

Geometry is identical across a model's nozzle variants, so the table is keyed by
model rather than by preset.
"""

from __future__ import annotations

Polygon = tuple[tuple[float, float], ...]

#: ``printer_model`` -> (printable_area, extruder_printable_area, bed_exclude_area,
#: wrapping_exclude_area, printable_height)
PLATE_PROFILES: dict[str, tuple[Polygon, tuple[Polygon, ...], Polygon, Polygon, float]] = {
    "Bambu Lab A1": (((0.0, 0.0), (256.0, 0.0), (256.0, 256.0), (0.0, 256.0)), (), (), (), 256.0),
    "Bambu Lab A1 mini": (
        ((0.0, 0.0), (180.0, 0.0), (180.0, 180.0), (0.0, 180.0)),
        (),
        (),
        (),
        180.0,
    ),
    "Bambu Lab A2L": (((0.0, 0.0), (330.0, 0.0), (330.0, 320.0), (0.0, 320.0)), (), (), (), 325.0),
    "Bambu Lab H2C": (
        ((0.0, 0.0), (330.0, 0.0), (330.0, 320.0), (0.0, 320.0)),
        (
            ((0.0, 0.0), (325.0, 0.0), (325.0, 320.0), (0.0, 320.0)),
            ((25.0, 0.0), (330.0, 0.0), (330.0, 320.0), (25.0, 320.0)),
        ),
        (),
        ((145.0, 310.0), (251.0, 310.0), (251.0, 326.0), (145.0, 326.0)),
        325.0,
    ),
    "Bambu Lab H2D": (
        ((0.0, 0.0), (350.0, 0.0), (350.0, 320.0), (0.0, 320.0)),
        (
            ((0.0, 0.0), (325.0, 0.0), (325.0, 320.0), (0.0, 320.0)),
            ((25.0, 0.0), (350.0, 0.0), (350.0, 320.0), (25.0, 320.0)),
        ),
        (),
        ((145.0, 310.0), (256.0, 310.0), (256.0, 326.0), (145.0, 326.0)),
        325.0,
    ),
    "Bambu Lab H2D Pro": (
        ((0.0, 0.0), (350.0, 0.0), (350.0, 320.0), (0.0, 320.0)),
        (
            ((0.0, 0.0), (325.0, 0.0), (325.0, 320.0), (0.0, 320.0)),
            ((25.0, 0.0), (350.0, 0.0), (350.0, 320.0), (25.0, 320.0)),
        ),
        (),
        ((145.0, 310.0), (256.0, 310.0), (256.0, 326.0), (145.0, 326.0)),
        325.0,
    ),
    "Bambu Lab H2S": (
        ((0.0, 0.0), (340.0, 0.0), (340.0, 320.0), (0.0, 320.0)),
        (),
        (),
        ((172.3, 302.0), (232.5, 302.0), (232.5, 322.0), (172.3, 322.0)),
        340.0,
    ),
    "Bambu Lab P1P": (
        ((0.0, 0.0), (256.0, 0.0), (256.0, 256.0), (0.0, 256.0)),
        (),
        ((0.0, 0.0), (18.0, 0.0), (18.0, 28.0), (0.0, 28.0)),
        (),
        250.0,
    ),
    "Bambu Lab P1S": (
        ((0.0, 0.0), (256.0, 0.0), (256.0, 256.0), (0.0, 256.0)),
        (),
        ((0.0, 0.0), (18.0, 0.0), (18.0, 28.0), (0.0, 28.0)),
        (),
        250.0,
    ),
    "Bambu Lab P2S": (
        ((0.0, 0.0), (256.0, 0.0), (256.0, 256.0), (0.0, 256.0)),
        (),
        (),
        ((153.0, 256.0), (216.0, 256.0), (216.0, 235.0), (153.0, 235.0)),
        256.0,
    ),
    "Bambu Lab X1": (
        ((0.0, 0.0), (256.0, 0.0), (256.0, 256.0), (0.0, 256.0)),
        (),
        ((0.0, 0.0), (18.0, 0.0), (18.0, 28.0), (0.0, 28.0)),
        (),
        250.0,
    ),
    "Bambu Lab X1 Carbon": (
        ((0.0, 0.0), (256.0, 0.0), (256.0, 256.0), (0.0, 256.0)),
        (),
        ((0.0, 0.0), (18.0, 0.0), (18.0, 28.0), (0.0, 28.0)),
        (),
        250.0,
    ),
    "Bambu Lab X1E": (
        ((0.0, 0.0), (256.0, 0.0), (256.0, 256.0), (0.0, 256.0)),
        (),
        ((0.0, 0.0), (18.0, 0.0), (18.0, 28.0), (0.0, 28.0)),
        (),
        250.0,
    ),
    "Bambu Lab X2D": (
        ((0.0, 0.0), (256.0, 0.0), (256.0, 256.0), (0.0, 256.0)),
        (
            ((0.0, 0.0), (256.0, 0.0), (256.0, 256.0), (0.0, 256.0)),
            ((20.5, 0.0), (256.0, 0.0), (256.0, 256.0), (20.5, 256.0)),
        ),
        (),
        (),
        261.0,
    ),
}

#: Short codes Bambuddy reports in ``Printer.model`` that are not the model name
#: with "Bambu Lab " removed.
EXTRA_ALIASES: dict[str, str] = {
    "A1M": "Bambu Lab A1 mini",
    "H2DP": "Bambu Lab H2D Pro",
    "X1C": "Bambu Lab X1 Carbon",
}
