from __future__ import annotations

import asyncio
import logging
import secrets
from collections.abc import Mapping, Sequence
from dataclasses import dataclass, field
from pathlib import Path
from typing import cast

import trimesh

from scadbuddy.core.config import Config
from scadbuddy.render.colours import CSS_COLOURS
from scadbuddy.render.runner import OpenSCADError, render_3mf
from scadbuddy.render.schema import CustomizerSchema, ParamValue
from scadbuddy.render.split import split_by_material

logger = logging.getLogger(__name__)

#: The wrapper has to live beside the model so its ``include <>`` resolves, which
#: puts a transient .scad inside the directory `provenance.source_version` hashes —
#: it skips anything with this prefix, so the two must stay in step. Since #90 that
#: directory is also a git repository, so `library/history.py` writes this same
#: prefix into its .gitignore: three places, one constant.
WRAPPER_PREFIX = "_scadbuddy_solid_"
#: An uploaded asset staged beside the model for one render (#204). It shares the
#: wrapper's prefix so the same three places skip it -- the source hash, the
#: .gitignore and a duplicate's copy -- without a second constant to keep in step.
STAGED_ASSET_PREFIX = f"{WRAPPER_PREFIX}asset_"
#: How a warning ends when a colour fell back to its open split mesh. The geometry
#: analysis (`render/geometry.py`) reads it back to know which parts are not closed
#: solids, so an open edge there is not reported as a defect of the model.
SPLIT_FALLBACK = "used the split mesh"

# A user-defined `color` module shadows the builtin, so a wrapper that keeps only the
# children whose innermost color() matches a target renders that colour on its own --
# as one closed solid, instead of the open shell a material split leaves behind.
WRAPPER_PRELUDE = """// Generated by ScadBuddy. Renders one colour of the model as a closed solid.
_sb_targets = [];
function _sb_up(s) =
  chr([for (i = [0:len(s) - 1]) let (o = ord(s[i])) (o >= 97 && o <= 122) ? o - 32 : o]);
function _sb_low(s) =
  chr([for (i = [0:len(s) - 1]) let (o = ord(s[i])) (o >= 65 && o <= 90) ? o + 32 : o]);
function _sb_h2(v) =
  let (n = round(v * 255), d = "0123456789ABCDEF") str(d[floor(n / 16)], d[n % 16]);
function _sb_hex(c) =
  is_string(c) ? (c[0] == "#" ? _sb_up(c) : str("name:", _sb_low(c)))
               : str("#", _sb_h2(c[0]), _sb_h2(c[1]), _sb_h2(c[2]));
function _sb_match(h) = len([for (t = _sb_targets) if (t == h) 1]) > 0;
module color(c, alpha = 1) { if (_sb_match(_sb_hex(c))) children(); }
"""


@dataclass
class SolidRender:
    meshes: dict[str, trimesh.Trimesh] = field(default_factory=dict)
    warnings: list[str] = field(default_factory=list)


def wrapper_source(model_name: str) -> str:
    return f"{WRAPPER_PRELUDE}include <{model_name}>\n"


def targets_for(colour: str) -> list[str]:
    """Every literal a model could have written to produce this material colour."""
    upper = "#" + colour.lstrip("#").upper()
    names = [f"name:{name}" for name, value in CSS_COLOURS.items() if value == upper]
    return [upper, *names]


def _vector_literal(values: Sequence[str]) -> str:
    return "[" + ", ".join(f'"{value}"' for value in values) + "]"


def _solid_mesh(path: Path) -> trimesh.Trimesh | None:
    """The wrapper render's geometry as one mesh, or None when it drew nothing."""
    meshes = [part.mesh for part in split_by_material(path)]
    if not meshes:
        return None
    if len(meshes) == 1:
        return meshes[0]
    return cast(trimesh.Trimesh, trimesh.util.concatenate(meshes))


async def render_solids(
    scad_path: Path,
    schema: CustomizerSchema,
    params: Mapping[str, ParamValue],
    colours: Sequence[str],
    work_dir: Path,
    *,
    config: Config,
    extra_defines: Sequence[str] = (),
) -> SolidRender:
    """One closed solid per colour, rendered ``config.solid_slots()`` at a time (#282).

    The result is in ``colours`` order whatever order the renders finish in. An
    OpenSCAD failure is a colour's fallback, never the job's (spec §6.3). Anything
    else -- or this coroutine being cancelled -- cancels every sibling, which kills
    its `openscad` (`run_openscad`), and the wrapper is removed only once they have
    all stopped -- except a mesh parse already running in its worker thread, which a
    cancel abandons rather than stops (it is bounded work). Each render's
    `SCADBUDDY_RENDER_TIMEOUT` starts when its process does, so a colour waiting for a
    slot is not charged for the wait. ``extra_defines`` reach every wrapper render
    too: a multi-plate render passes its ``$plate`` this way (spec §6.4).
    """
    slots = asyncio.Semaphore(config.solid_slots())
    wrapper = scad_path.parent / f"{WRAPPER_PREFIX}{secrets.token_hex(8)}.scad"
    stopping = False

    async def solid(index: int, colour: str) -> trimesh.Trimesh | str:
        """The colour's solid, or the warning that says why it has none."""
        nonlocal stopping
        out_path = work_dir / f"solid_{index}.3mf"
        targets = _vector_literal(targets_for(colour))
        async with slots:
            # A failing sibling frees its slot before the group's cancellation
            # reaches the colour waiting on it: do not start an openscad to kill it.
            if stopping:
                raise asyncio.CancelledError
            try:
                await render_3mf(
                    wrapper,
                    schema,
                    params,
                    out_path,
                    config=config,
                    extra_defines=[*extra_defines, "-D", f"_sb_targets={targets}"],
                )
                # Parsing and joining the mesh is CPU work: off the loop, which every
                # other job's drain, the queue and /healthz share -- and several colours
                # can now finish their `openscad` at nearly the same moment.
                mesh = await asyncio.to_thread(_solid_mesh, out_path)
            except OpenSCADError as error:
                return f"{colour}: no closed solid ({error}); {SPLIT_FALLBACK}"
            except BaseException:
                stopping = True
                raise
        if mesh is None:
            return f"{colour}: the solid render was empty; {SPLIT_FALLBACK}"
        return mesh

    wrapper.write_text(wrapper_source(scad_path.name), encoding="utf-8")
    try:
        async with asyncio.TaskGroup() as group:
            tasks = [
                group.create_task(solid(index, colour))
                for index, colour in enumerate(colours, start=1)
            ]
    except BaseExceptionGroup as group_error:
        # The job's error is the colour's own, not "unhandled errors in a TaskGroup".
        # Two colours can fail before the cancellation lands; the job can carry only
        # one error, so the others are logged rather than lost.
        first, *others = group_error.exceptions
        for other in others:
            logger.error(
                "another colour's solid render failed too",
                exc_info=(type(other), other, other.__traceback__),
            )
        raise first from None
    finally:
        wrapper.unlink(missing_ok=True)

    result = SolidRender()
    for colour, task in zip(colours, tasks, strict=True):
        outcome = task.result()
        if isinstance(outcome, str):
            result.warnings.append(outcome)
        else:
            result.meshes[colour] = outcome
    return result
