from __future__ import annotations

import secrets
from collections.abc import Mapping, Sequence
from dataclasses import dataclass, field
from pathlib import Path
from typing import cast

import trimesh

from scadbuddy.core.config import Config
from scadbuddy.render.colours import CSS_COLOURS
from scadbuddy.render.runner import OpenSCADError, render_3mf
from scadbuddy.render.schema import CustomizerSchema, ParamValue
from scadbuddy.render.split import split_by_material

#: The wrapper has to live beside the model so its ``include <>`` resolves, which
#: puts a transient .scad inside the directory `provenance.source_version` hashes —
#: it skips anything with this prefix, so the two must stay in step. Since #90 that
#: directory is also a git repository, so `library/history.py` writes this same
#: prefix into its .gitignore: three places, one constant.
WRAPPER_PREFIX = "_scadbuddy_solid_"

# A user-defined `color` module shadows the builtin, so a wrapper that keeps only the
# children whose innermost color() matches a target renders that colour on its own --
# as one closed solid, instead of the open shell a material split leaves behind.
WRAPPER_PRELUDE = """// Generated by ScadBuddy. Renders one colour of the model as a closed solid.
_sb_targets = [];
function _sb_up(s) =
  chr([for (i = [0:len(s) - 1]) let (o = ord(s[i])) (o >= 97 && o <= 122) ? o - 32 : o]);
function _sb_low(s) =
  chr([for (i = [0:len(s) - 1]) let (o = ord(s[i])) (o >= 65 && o <= 90) ? o + 32 : o]);
function _sb_h2(v) =
  let (n = round(v * 255), d = "0123456789ABCDEF") str(d[floor(n / 16)], d[n % 16]);
function _sb_hex(c) =
  is_string(c) ? (c[0] == "#" ? _sb_up(c) : str("name:", _sb_low(c)))
               : str("#", _sb_h2(c[0]), _sb_h2(c[1]), _sb_h2(c[2]));
function _sb_match(h) = len([for (t = _sb_targets) if (t == h) 1]) > 0;
module color(c, alpha = 1) { if (_sb_match(_sb_hex(c))) children(); }
"""


@dataclass
class SolidRender:
    meshes: dict[str, trimesh.Trimesh] = field(default_factory=dict)
    warnings: list[str] = field(default_factory=list)


def wrapper_source(model_name: str) -> str:
    return f"{WRAPPER_PRELUDE}include <{model_name}>\n"


def targets_for(colour: str) -> list[str]:
    """Every literal a model could have written to produce this material colour."""
    upper = "#" + colour.lstrip("#").upper()
    names = [f"name:{name}" for name, value in CSS_COLOURS.items() if value == upper]
    return [upper, *names]


def _vector_literal(values: Sequence[str]) -> str:
    return "[" + ", ".join(f'"{value}"' for value in values) + "]"


async def render_solids(
    scad_path: Path,
    schema: CustomizerSchema,
    params: Mapping[str, ParamValue],
    colours: Sequence[str],
    work_dir: Path,
    *,
    config: Config,
) -> SolidRender:
    result = SolidRender()
    wrapper = scad_path.parent / f"{WRAPPER_PREFIX}{secrets.token_hex(8)}.scad"
    wrapper.write_text(wrapper_source(scad_path.name), encoding="utf-8")
    try:
        for index, colour in enumerate(colours, start=1):
            out_path = work_dir / f"solid_{index}.3mf"
            targets = _vector_literal(targets_for(colour))
            try:
                await render_3mf(
                    wrapper,
                    schema,
                    params,
                    out_path,
                    config=config,
                    extra_defines=["-D", f"_sb_targets={targets}"],
                )
                parts = split_by_material(out_path)
            except OpenSCADError as error:
                result.warnings.append(f"{colour}: no closed solid ({error}); used the split mesh")
                continue
            if not parts:
                result.warnings.append(f"{colour}: the solid render was empty; used the split mesh")
                continue
            meshes = [part.mesh for part in parts]
            result.meshes[colour] = (
                meshes[0]
                if len(meshes) == 1
                else cast(trimesh.Trimesh, trimesh.util.concatenate(meshes))
            )
    finally:
        wrapper.unlink(missing_ok=True)
    return result
