#!/usr/bin/env python3
"""Regenerate ``scadbuddy/render/plate_profiles.py`` from Bambu Studio's own profiles.

The plate a 3MF is laid out on is not a number to be recalled — it is
``printable_area`` / ``extruder_printable_area`` / ``bed_exclude_area`` /
``wrapping_exclude_area`` / ``printable_height`` in
``resources/profiles/BBL/machine/*.json`` in bambulab/BambuStudio, resolved
through each preset's ``inherits`` chain. This script reads them and writes the
table; nothing here is typed in by hand.

``extruder_printable_height`` is read by nothing, deliberately: see the
``printable_height`` entry in the generated module's docstring (#122).

The bed types each model takes (#83) come from the same directory's
``machine_model`` files: every ``curr_bed_type`` value less the model's
``not_support_bed_type``.

Usage::

    uv run python scripts/generate_plate_profiles.py          # downloads master
    uv run python scripts/generate_plate_profiles.py <path>   # a local checkout

``<path>`` may be a BambuStudio checkout or the ``resources/profiles/BBL``
directory inside one.
"""

from __future__ import annotations

import io
import json
import subprocess
import sys
import tarfile
import urllib.request
from pathlib import Path
from typing import Any

TARBALL = "https://codeload.github.com/bambulab/BambuStudio/tar.gz/refs/heads/master"
OUTPUT = Path(__file__).resolve().parent.parent / "scadbuddy" / "render" / "plate_profiles.py"

#: Bambuddy reports ``Printer.model`` as Bambu's marketing short code. Most of them
#: are the machine profile's name with the "Bambu Lab " prefix dropped, which
#: :func:`scadbuddy.render.plate.plate_for` derives; these three are not.
EXTRA_ALIASES = {
    "X1C": "Bambu Lab X1 Carbon",
    "A1M": "Bambu Lab A1 mini",
    "H2DP": "Bambu Lab H2D Pro",
}

#: ``curr_bed_type`` in ``src/libslic3r/PrintConfig.cpp``: each value with the label
#: Bambu Studio shows for it, in its order. ``not_support_bed_type`` names the
#: *labels* (``Plater.cpp`` compares it with ``enum_labels``), which is why both are
#: kept; the value is what a slice request's ``bed_type`` carries.
BED_TYPE_LABELS = {
    "Cool Plate": "Cool Plate",
    "Engineering Plate": "Engineering Plate",
    "High Temp Plate": "Smooth PEI Plate / High Temp Plate",
    "Textured PEI Plate": "Textured PEI Plate",
    "Supertack Plate": "Bambu Cool Plate SuperTack",
}

HEADER = '''"""Plate geometry per Bambu printer model.

GENERATED by ``scripts/generate_plate_profiles.py`` from bambulab/BambuStudio's
``resources/profiles/BBL/machine/*.json``. Do not edit by hand.

Each entry is keyed by the machine profile's ``printer_model`` and carries, in
millimetres, the values those profiles declare:

``printable_area``
    the bed polygon every extruder shares as an outer bound.
``extruder_printable_area``
    one polygon per extruder, empty for a single-extruder machine. On the H2
    series the two differ — extruder 2 cannot reach the left edge — and that gap
    is what makes a default-placed prime tower unprintable.
``bed_exclude_area``
    the front-left cutout the X1/P1 series uses to cut filament.
``wrapping_exclude_area``
    the strip the H2/P2S series probes for clumping ("wrapping") at the back of
    the bed. It is a no-print zone *only while* the process option
    ``enable_wrapping_detection`` is on — ``Print.cpp``'s
    ``layered_print_cleareance_valid`` then refuses a prime tower that touches it
    ("Prime Tower is too close to clumping detection area, and collisions will be
    caused") — and inert otherwise. That option lives in the process preset
    Bambuddy slices with, which ScadBuddy never sees, so the prime tower always
    avoids it (#122).
``printable_height``
    the Z limit. The 3MF writer states it in ``project_settings.config``:
    once a file claims BambuStudio identity the CLI dereferences that option
    without a null check, so it is required rather than informational (#110).
    ``extruder_printable_height`` (per extruder; the H2C's are 320 and 325) is
    deliberately not read (#122): nothing uses Z as a constraint, and the one
    consumer writes this value back under the key ``printable_height``, where
    the per-extruder minimum would misstate the profile. If Z ever becomes a
    placement constraint, read the minimum across extruders then.

Geometry is identical across a model's nozzle variants, so the table is keyed by
model rather than by preset.

:data:`BED_TYPES` is, per model, every ``curr_bed_type`` value its
``machine_model`` profile does not list under ``not_support_bed_type`` — the
plates Bambu Studio's own bed picker offers for that printer (#83).
"""

from __future__ import annotations

Polygon = tuple[tuple[float, float], ...]

#: ``printer_model`` -> (printable_area, extruder_printable_area, bed_exclude_area,
#: wrapping_exclude_area, printable_height)
PLATE_PROFILES: dict[str, tuple[Polygon, tuple[Polygon, ...], Polygon, Polygon, float]] = {
'''

FOOTER = """}}

#: Short codes Bambuddy reports in ``Printer.model`` that are not the model name
#: with "Bambu Lab " removed.
EXTRA_ALIASES: dict[str, str] = {aliases}

#: ``curr_bed_type`` value -> the label Bambu Studio shows for it.
BED_TYPE_LABELS: dict[str, str] = {labels}

#: ``printer_model`` -> the ``curr_bed_type`` values that model takes.
BED_TYPES: dict[str, tuple[str, ...]] = {bed_types}
"""


def _load_profiles(root: Path) -> dict[str, Path]:
    machine = root if root.name == "machine" else root / "machine"
    if not machine.is_dir():
        for candidate in (root / "resources" / "profiles" / "BBL" / "machine",):
            if candidate.is_dir():
                machine = candidate
                break
    if not machine.is_dir():
        raise SystemExit(f"no BBL machine profile directory under {root}")
    return {path.stem: path for path in machine.glob("*.json")}


def _resolve(stem: str, files: dict[str, Path]) -> dict[str, Any]:
    """Flatten one preset's ``inherits`` chain, nearest wins."""
    profile: dict[str, Any] = json.loads(files[stem].read_text(encoding="utf-8"))
    parent = profile.get("inherits")
    if not parent or parent not in files:
        return profile
    merged = _resolve(parent, files)
    merged.update({key: value for key, value in profile.items() if key != "inherits"})
    return merged


def _point(text: str) -> tuple[float, float]:
    x, y = text.strip().split("x")
    return (float(x), float(y))


def _polygon(entries: list[str] | None) -> tuple[tuple[float, float], ...]:
    """``["0x0", "330x0", ...]`` and ``["0x0,325x0,..."]`` are both point lists."""
    if not entries:
        return ()
    points: list[tuple[float, float]] = []
    for entry in entries:
        points.extend(_point(part) for part in entry.split(",") if part.strip())
    return tuple(points)


def _download() -> Path:
    print(f"downloading {TARBALL} ...", file=sys.stderr)
    with urllib.request.urlopen(TARBALL) as response:
        payload = response.read()
    destination = Path(".bambustudio-profiles")
    with tarfile.open(fileobj=io.BytesIO(payload)) as archive:
        members = [
            member
            for member in archive.getmembers()
            if "/resources/profiles/BBL/machine/" in member.name
        ]
        archive.extractall(destination, members=members, filter="data")
    return next(destination.glob("*/resources/profiles/BBL/machine"))


def collect(root: Path) -> dict[str, tuple[Any, ...]]:
    files = _load_profiles(root)
    table: dict[str, tuple[Any, ...]] = {}
    for stem in sorted(files):
        raw = json.loads(files[stem].read_text(encoding="utf-8"))
        if raw.get("type") != "machine" or " template " in stem:
            continue
        resolved = _resolve(stem, files)
        model = resolved.get("printer_model")
        if not model:
            continue
        exclusion = _polygon(resolved.get("bed_exclude_area"))
        wrapping = _polygon(resolved.get("wrapping_exclude_area"))
        for key, polygon in (("bed_exclude_area", exclusion), ("wrapping_exclude_area", wrapping)):
            if len(polygon) not in (0, 4):
                # The table holds one polygon per model and the writer reduces it to
                # a bounding rectangle, so several areas concatenated into one list
                # would silently become one oversized rectangle spanning the gap
                # between them. Every BBL profile has a single rectangle today; fail
                # loudly if that ends.
                raise SystemExit(
                    f"{model}: {key} has {len(polygon)} points, which is not one "
                    "rectangle; the table's single-polygon shape no longer holds"
                )
        entry = (
            _polygon(resolved.get("printable_area")),
            tuple(_polygon([one]) for one in resolved.get("extruder_printable_area") or []),
            exclusion,
            wrapping,
            float(resolved.get("printable_height") or 0.0),
        )
        previous = table.setdefault(model, entry)
        if previous != entry:
            raise SystemExit(
                f"{model}: nozzle variants disagree on plate geometry; the table's "
                "one-entry-per-model shape no longer holds"
            )
    return table


def collect_bed_types(root: Path) -> dict[str, tuple[str, ...]]:
    by_label = {label: value for value, label in BED_TYPE_LABELS.items()}
    table: dict[str, tuple[str, ...]] = {}
    for path in _load_profiles(root).values():
        raw = json.loads(path.read_text(encoding="utf-8"))
        if raw.get("type") != "machine_model":
            continue
        refused = [label for label in raw.get("not_support_bed_type", "").split(";") if label]
        unknown = [label for label in refused if label not in by_label]
        if unknown:
            raise SystemExit(
                f"{raw['name']}: not_support_bed_type names {unknown}, which is not a "
                "curr_bed_type label this script knows; re-read PrintConfig.cpp"
            )
        excluded = {by_label[label] for label in refused}
        table[raw["name"]] = tuple(value for value in BED_TYPE_LABELS if value not in excluded)
    return table


def _mapping(entries: dict[str, Any]) -> str:
    return (
        "{\n" + "".join(f"    {key!r}: {_render(value)},\n" for key, value in entries.items()) + "}"
    )


def _render(value: Any) -> str:
    if isinstance(value, tuple):
        inner = ", ".join(_render(item) for item in value)
        return f"({inner},)" if len(value) == 1 else f"({inner})"
    if isinstance(value, float):
        return repr(round(value, 4))
    return repr(value)


def main() -> None:
    root = Path(sys.argv[1]) if len(sys.argv) > 1 else _download()
    table = collect(root)
    if not table:
        raise SystemExit(f"no machine profiles found under {root}")
    body = "".join(f"    {model!r}: {_render(entry)},\n" for model, entry in sorted(table.items()))
    bed_types = collect_bed_types(root)
    missing = sorted(set(table) - set(bed_types))
    if missing:
        raise SystemExit(f"no machine_model profile for {missing}, so no bed types for them")
    footer = FOOTER.format(
        aliases=_mapping(dict(sorted(EXTRA_ALIASES.items()))),
        labels=_mapping(BED_TYPE_LABELS),
        bed_types=_mapping({model: bed_types[model] for model in sorted(table)}),
    )
    OUTPUT.write_text(HEADER + body + footer, encoding="utf-8")
    # The rows are far past the 100-column limit as one line each; ruff owns the
    # wrapping so a regeneration lands already formatted rather than failing CI.
    subprocess.run(["ruff", "format", str(OUTPUT)], check=True)
    print(f"wrote {OUTPUT} with {len(table)} models", file=sys.stderr)


if __name__ == "__main__":
    main()
