/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/fonts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Installed font families */
        get: operations["get_fonts_api_v1_fonts_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/fonts/catalogue": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Search the Google Fonts catalogue */
        get: operations["get_catalogue_api_v1_fonts_catalogue_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/fonts/install": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Install a family onto the data volume */
        post: operations["install_font_api_v1_fonts_install_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/jobs/{job_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Render job state */
        get: operations["get_job_api_v1_jobs__job_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/jobs/{job_id}/preview.glb": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Render job preview mesh */
        get: operations["get_job_preview_api_v1_jobs__job_id__preview_glb_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/models": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List models */
        get: operations["list_models_api_v1_models_get"];
        put?: never;
        /** Upload a model */
        post: operations["create_model_api_v1_models_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/models/{slug}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Model metadata */
        get: operations["get_model_api_v1_models__slug__get"];
        put?: never;
        post?: never;
        /** Delete a model */
        delete: operations["delete_model_api_v1_models__slug__delete"];
        options?: never;
        head?: never;
        /** Edit model metadata */
        patch: operations["patch_model_api_v1_models__slug__patch"];
        trace?: never;
    };
    "/api/v1/models/{slug}/outputs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Output history
         * @description Details, not summaries: the history page shows each output's parameter diff, and
         *     a summary list would make it fetch every row again one at a time.
         */
        get: operations["list_outputs_api_v1_models__slug__outputs_get"];
        put?: never;
        /** Persist a finished render */
        post: operations["create_output_api_v1_models__slug__outputs_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/models/{slug}/render": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Queue a render */
        post: operations["render_model_api_v1_models__slug__render_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/models/{slug}/schema": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Customizer schema */
        get: operations["get_schema_api_v1_models__slug__schema_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/models/{slug}/source": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Raw OpenSCAD source */
        get: operations["get_source_api_v1_models__slug__source_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/models/{slug}/thumbnail": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Model thumbnail */
        get: operations["get_thumbnail_api_v1_models__slug__thumbnail_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/outputs/{output_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Output detail */
        get: operations["get_output_api_v1_outputs__output_id__get"];
        put?: never;
        post?: never;
        /** Delete an output */
        delete: operations["delete_output_api_v1_outputs__output_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/outputs/{output_id}/model.3mf": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Download the 3MF */
        get: operations["download_output_api_v1_outputs__output_id__model_3mf_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/outputs/{output_id}/send": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Send the 3MF to Bambuddy
         * @description Upload ``model.3mf`` to the configured library folder and, in ``queue`` mode,
         *     slice and queue it.
         *
         *     The file is read from the PVC and pushed by the server, so the API key never
         *     reaches the browser. A re-send replaces the file Bambuddy already holds rather
         *     than adding a second copy.
         */
        post: operations["send_output_to_bambuddy_api_v1_outputs__output_id__send_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/outputs/{output_id}/thumbnail": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Output thumbnail */
        get: operations["get_output_thumbnail_api_v1_outputs__output_id__thumbnail_get"];
        /** Upload the canvas capture */
        put: operations["put_output_thumbnail_api_v1_outputs__output_id__thumbnail_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/print/models/{slug}/pipeline": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Remember this model's pipeline
         * @description Needs no Bambuddy: this is ScadBuddy's own preference, stored per slug.
         */
        put: operations["put_model_pipeline_api_v1_print_models__slug__pipeline_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/print/models/{slug}/pipelines": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Pipelines, with this model's default */
        get: operations["get_model_pipelines_api_v1_print_models__slug__pipelines_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/print/outputs/{output_id}/eligibility": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Which pipelines would accept this output
         * @description Uploads the 3MF if Bambuddy does not have it yet, then asks each pipeline.
         *
         *     Bambuddy judges a *library file*, so there is no eligibility answer before an
         *     upload. The upload happens once per output: an output is immutable, so a recorded
         *     ``library_file_id`` still describes this 3MF.
         *
         *     Every report comes back as Bambuddy sent it, including ``printer_reports`` — under
         *     ``target_kind="printer_class"`` that is where the per-printer reasons are, and the
         *     top-level ``ok`` means only that *some* printer passes.
         */
        post: operations["post_eligibility_api_v1_print_outputs__output_id__eligibility_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/print/outputs/{output_id}/run": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Run a pipeline for this output
         * @description ``POST /api/v1/slicer-pipelines/{id}/run`` with ``copies`` and an explicit
         *     ``force``.
         *
         *     Without ``pipeline_id`` the model's own default is used, then the global one. A
         *     blocking eligibility issue is Bambuddy's 409, whose body this passes through as the
         *     ``bambuddy_body`` problem extension; ``force: true`` runs anyway and Bambuddy records
         *     ``eligibility_overridden``.
         *
         *     There is deliberately no printer here. ``PipelineRunRequest`` carries none, so a
         *     class-targeted pipeline fans out by its own ``fanout_strategy`` and reports the
         *     printer per copy in ``run.jobs[]``.
         */
        post: operations["post_run_api_v1_print_outputs__output_id__run_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/print/pipelines": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create a pipeline from presets
         * @description ``POST /api/v1/slicer-pipelines/`` verbatim.
         *
         *     ``SlicerPipelineCreate`` carries no target or fanout fields, so the new pipeline
         *     cannot be created pre-aimed at a printer — Bambuddy targets it and the response
         *     reports what it chose. Re-targeting is a ``PUT`` ScadBuddy does not make.
         */
        post: operations["post_pipeline_api_v1_print_pipelines_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/print/presets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Presets a new pipeline can be built from
         * @description Printer presets and bed types, plus — once a printer preset is named — the
         *     process and filament presets compatible with it.
         *
         *     The filter is server-side on purpose: the live instance holds ~4000 process and
         *     filament presets across the cloud and standard tiers, which is not a payload to
         *     hand a browser so it can filter them itself. Nozzle diameter is not a field
         *     anywhere; it lives in the process preset's *name* ("… H2C 0.2 nozzle"), which is
         *     why the form picks a process preset rather than a diameter.
         */
        get: operations["get_presets_api_v1_print_presets_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/settings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Bambuddy connection */
        get: operations["get_settings_api_v1_settings_get"];
        /** Update the connection */
        put: operations["put_settings_api_v1_settings_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/settings/register-sidebar": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Add ScadBuddy to Bambuddy's sidebar
         * @description Upsert the ``Customize`` External Link by name.
         *
         *     Bambuddy renders a link with ``open_in_new_tab: false`` inside its own shell, in a
         *     sandboxed iframe at ``/external/{id}`` — so ScadBuddy appears as a sidebar page
         *     rather than a tab.
         */
        post: operations["post_register_sidebar_api_v1_settings_register_sidebar_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/settings/targets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Folders, pipelines and printers to choose from */
        get: operations["get_targets_api_v1_settings_targets_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/settings/test": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Verify the API key
         * @description ``GET /api/v1/printers/`` on Bambuddy — note the trailing slash, without which
         *     1.2.5.5 answers 404.
         *
         *     A reachable Bambuddy that refuses the key is a *result* (``ok: false``), not an
         *     error; only a missing URL — nothing to test at all — is still a 409.
         */
        post: operations["test_settings_api_v1_settings_test_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Liveness */
        get: operations["healthz_healthz_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * BambuddyTargets
         * @description Everything the settings page needs to fill its pickers.
         */
        BambuddyTargets: {
            /** Folders */
            folders?: components["schemas"]["Folder"][];
            /** Pipelines */
            pipelines?: components["schemas"]["Pipeline"][];
            /** Printers */
            printers?: components["schemas"]["Printer"][];
        };
        /** Body_create_model_api_v1_models_post */
        Body_create_model_api_v1_models_post: {
            /** Description */
            description?: string | null;
            /**
             * File
             * @description The .scad source
             */
            file: string;
            /** Name */
            name?: string | null;
            /**
             * Readme
             * @description Optional README.md
             */
            readme?: string | null;
            /**
             * Tags
             * @description JSON array or comma-separated
             */
            tags?: string | null;
            /**
             * Thumbnail
             * @description Optional PNG
             */
            thumbnail?: string | null;
        };
        /** Body_put_output_thumbnail_api_v1_outputs__output_id__thumbnail_put */
        Body_put_output_thumbnail_api_v1_outputs__output_id__thumbnail_put: {
            /**
             * File
             * @description PNG captured by the viewer
             */
            file: string;
        };
        /** BoundingBox */
        BoundingBox: {
            /** Max */
            max: [
                number,
                number,
                number
            ];
            /** Min */
            min: [
                number,
                number,
                number
            ];
            /** Size */
            size: [
                number,
                number,
                number
            ];
        };
        /** CatalogueEntry */
        CatalogueEntry: {
            /**
             * Category
             * @default
             */
            category: string;
            /** Family */
            family: string;
            /**
             * Installed
             * @default false
             */
            installed: boolean;
            /** Popularity */
            popularity?: number | null;
            /** Variants */
            variants?: components["schemas"]["FontVariant"][];
        };
        /** ConnectionTest */
        ConnectionTest: {
            /** Detail */
            detail: string;
            /** Ok */
            ok: boolean;
            /** Printers */
            printers?: components["schemas"]["Printer"][];
        };
        /** CreateOutputRequest */
        CreateOutputRequest: {
            /** Job Id */
            job_id: string;
            /** Name */
            name?: string | null;
        };
        /** CustomizerSchema */
        CustomizerSchema: {
            /** Groups */
            groups?: string[];
            /** Parameters */
            parameters?: components["schemas"]["Parameter"][];
            /**
             * Source Sha256
             * @default
             */
            source_sha256: string;
            /** Title */
            title?: string | null;
        };
        /**
         * EligibilityCheck
         * @description ``pipeline_ids`` omitted means every pipeline Bambuddy has.
         */
        EligibilityCheck: {
            /** Pipeline Ids */
            pipeline_ids?: number[] | null;
        };
        /**
         * EligibilityIssue
         * @description ``kind`` is an open enum here on purpose — Bambuddy adds kinds between
         *     releases and an unknown one must still render, not 502 the whole report.
         */
        EligibilityIssue: {
            /** Actual */
            actual?: string | null;
            /** Expected */
            expected?: string | null;
            /** Kind */
            kind: string;
            /** Slot Index */
            slot_index?: number | null;
        };
        /** EligibilityOverview */
        EligibilityOverview: {
            /** Library File Id */
            library_file_id: number;
            /** Reports */
            reports?: components["schemas"]["PipelineReport"][];
        };
        /**
         * EligibilityReport
         * @description Returned by ``check-eligibility`` and, on a 409, by ``run``.
         *
         *     Under ``target_kind="printer_class"`` ``ok`` is true when *at least one* matching
         *     printer passes, and the per-printer detail moves to ``printer_reports`` — ``issues``
         *     then carries only class-level problems. Reading ``ok`` as "every printer is ready"
         *     is wrong for that target kind.
         */
        EligibilityReport: {
            /** Issues */
            issues?: components["schemas"]["EligibilityIssue"][];
            /** Ok */
            ok: boolean;
            /** Printer Reports */
            printer_reports?: components["schemas"]["PerPrinterReport"][];
            /**
             * Target Kind
             * @default specific_printer
             * @enum {string}
             */
            target_kind: "specific_printer" | "printer_class";
            /** Target Model Class */
            target_model_class?: string | null;
            /** Target Printer Id */
            target_printer_id?: number | null;
            /** Target Printer Name */
            target_printer_name?: string | null;
        };
        /** Folder */
        Folder: {
            /** Archive Id */
            archive_id?: number | null;
            /** File Count */
            file_count?: number | null;
            /** Id */
            id: number;
            /**
             * Is External
             * @default false
             */
            is_external: boolean;
            /** Name */
            name: string;
            /** Parent Id */
            parent_id?: number | null;
            /** Project Id */
            project_id?: number | null;
            /** Project Name */
            project_name?: string | null;
        };
        /**
         * FontCatalogueView
         * @description ``source`` says which of the two catalogue endpoints answered — the keyed
         *     Developer API or the keyless fonts.google.com metadata.
         */
        FontCatalogueView: {
            /**
             * Fetched At
             * Format: date-time
             */
            fetched_at: string;
            /** Fonts */
            fonts?: components["schemas"]["CatalogueEntry"][];
            /**
             * Source
             * @enum {string}
             */
            source: "developer-api" | "google-fonts-metadata";
            /** Total */
            total: number;
        };
        /** FontFamily */
        FontFamily: {
            /** Family */
            family: string;
            /** Styles */
            styles: string[];
        };
        /** FontVariant */
        FontVariant: {
            /**
             * Italic
             * @default false
             */
            italic: boolean;
            /**
             * Weight
             * @default 400
             */
            weight: number;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** Health */
        Health: {
            /** Data Dir Writable */
            data_dir_writable: boolean;
            /** Openscad Version */
            openscad_version: string | null;
            /**
             * Status
             * @enum {string}
             */
            status: "ok" | "degraded";
        };
        /** InstallRequest */
        InstallRequest: {
            /** Family */
            family: string;
            /**
             * Force
             * @default false
             */
            force: boolean;
        };
        /**
         * InstalledFamily
         * @description What an install left on disk, reported back with fontconfig's own style names.
         */
        InstalledFamily: {
            /** Family */
            family: string;
            /** Files */
            files?: string[];
            /** Licence */
            licence?: string | null;
            /** Styles */
            styles?: string[];
        };
        /** JobStatus */
        JobStatus: {
            bbox_mm?: components["schemas"]["BoundingBox"] | null;
            /** Colors */
            colors?: string[] | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Error */
            error?: string | null;
            /** Finished At */
            finished_at?: string | null;
            /** Id */
            id: string;
            /** Log Tail */
            log_tail?: string[];
            /** Params */
            params?: {
                [key: string]: boolean | number | string;
            };
            /** Parts */
            parts?: components["schemas"]["PartInfo"][] | null;
            /** Preview Url */
            preview_url?: string | null;
            /** Slug */
            slug: string;
            /** Started At */
            started_at?: string | null;
            /**
             * Status
             * @enum {string}
             */
            status: "pending" | "running" | "done" | "failed";
            /** Warnings */
            warnings?: string[] | null;
        };
        /** ModelPatch */
        ModelPatch: {
            /** Description */
            description?: string | null;
            /** Name */
            name?: string | null;
            /** Tags */
            tags?: string[] | null;
        };
        /** ModelRecord */
        ModelRecord: {
            /**
             * Description
             * @default
             */
            description: string;
            /** Has Readme */
            has_readme: boolean;
            /** Has Thumbnail */
            has_thumbnail: boolean;
            /** Name */
            name: string;
            /** Slug */
            slug: string;
            /** Source */
            source?: string | null;
            /** Tags */
            tags?: string[];
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** Option */
        Option: {
            /** Name */
            name: string;
            /** Value */
            value: boolean | number | string;
        };
        /** OutputDetail */
        OutputDetail: {
            bbox_mm: components["schemas"]["BoundingBox"];
            /** Colors */
            colors?: string[];
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Has Thumbnail */
            has_thumbnail: boolean;
            /** Id */
            id: string;
            /** Job Id */
            job_id: string;
            /** Library File Id */
            library_file_id?: number | null;
            /** Library File Plate */
            library_file_plate?: string | null;
            /** Name */
            name?: string | null;
            /** Params */
            params?: {
                [key: string]: boolean | number | string;
            };
            /** Parts */
            parts?: components["schemas"]["PartInfo"][];
            /** Pipeline Run Id */
            pipeline_run_id?: number | null;
            /** Queue Item Id */
            queue_item_id?: number | null;
            /** Slug */
            slug: string;
            /** Warnings */
            warnings?: string[];
        };
        /** Parameter */
        Parameter: {
            /** Caption */
            caption?: string | null;
            /**
             * Group
             * @default
             */
            group: string;
            /** Initial */
            initial?: boolean | number | string | null;
            /** Max */
            max?: number | null;
            /** Max Length */
            max_length?: number | null;
            /** Min */
            min?: number | null;
            /** Name */
            name: string;
            /** Options */
            options?: components["schemas"]["Option"][];
            /** Step */
            step?: number | null;
            /**
             * Type
             * @enum {string}
             */
            type: "number" | "integer" | "string" | "boolean" | "select" | "color" | "font" | "slider";
        };
        /** PartInfo */
        PartInfo: {
            /** Colour */
            colour: string;
            /** Extruder */
            extruder: number;
            /** Name */
            name: string;
            /** Watertight */
            watertight: boolean;
        };
        /** PerPrinterReport */
        PerPrinterReport: {
            /** Issues */
            issues?: components["schemas"]["EligibilityIssue"][];
            /** Ok */
            ok: boolean;
            /** Printer Id */
            printer_id: number;
            /** Printer Name */
            printer_name: string;
        };
        /** Pipeline */
        Pipeline: {
            /** Bed Type */
            bed_type?: string | null;
            /** Description */
            description?: string | null;
            /**
             * Fanout Strategy
             * @default max_parallel
             * @enum {string}
             */
            fanout_strategy: "max_parallel" | "fill_one_first" | "round_robin";
            /** Filament Presets */
            filament_presets?: components["schemas"]["PresetRef"][];
            /** Id */
            id: number;
            /** Name */
            name: string;
            printer_preset?: components["schemas"]["PresetRef"] | null;
            process_preset?: components["schemas"]["PresetRef"] | null;
            /**
             * Target Kind
             * @default printer_class
             * @enum {string}
             */
            target_kind: "specific_printer" | "printer_class";
            /** Target Model Class */
            target_model_class?: string | null;
            /** Target Printer Id */
            target_printer_id?: number | null;
        };
        /** PipelineChoices */
        PipelineChoices: {
            /** Default Pipeline Id */
            default_pipeline_id?: number | null;
            /** Global Pipeline Id */
            global_pipeline_id?: number | null;
            /** Model Pipeline Id */
            model_pipeline_id?: number | null;
            /** Pipelines */
            pipelines?: components["schemas"]["PipelineView"][];
            /** Printers */
            printers?: components["schemas"]["Printer"][];
        };
        /**
         * PipelineCreate
         * @description ``POST /api/v1/slicer-pipelines/``.
         *
         *     ``SlicerPipelineCreate`` carries **no** target or fanout fields even though
         *     ``SlicerPipelineResponse`` returns them — a pipeline is created against the
         *     defaults and re-targeted with ``PUT``, which ScadBuddy does not do.
         */
        PipelineCreate: {
            /** Bed Type */
            bed_type?: string | null;
            /** Description */
            description?: string | null;
            /** Filament Presets */
            filament_presets: components["schemas"]["PresetRef"][];
            /** Name */
            name: string;
            printer_preset: components["schemas"]["PresetRef"];
            process_preset: components["schemas"]["PresetRef"];
        };
        /** PipelineDefault */
        PipelineDefault: {
            /** Global Pipeline Id */
            global_pipeline_id?: number | null;
            /** Pipeline Id */
            pipeline_id?: number | null;
            /** Slug */
            slug: string;
        };
        /**
         * PipelineDefaultPatch
         * @description ``null`` clears this model's default, falling back to the global one.
         */
        PipelineDefaultPatch: {
            /** Pipeline Id */
            pipeline_id?: number | null;
        };
        /**
         * PipelineJob
         * @description One copy of a run: the queue entry it became and the printer it landed on.
         */
        PipelineJob: {
            /** Assigned Printer Id */
            assigned_printer_id?: number | null;
            /** Assigned Printer Name */
            assigned_printer_name?: string | null;
            /** Copy Index */
            copy_index: number;
            /** Error Message */
            error_message?: string | null;
            /** Id */
            id: number;
            /** Pipeline Run Id */
            pipeline_run_id: number;
            /** Queue Entry Id */
            queue_entry_id?: number | null;
            /** Status */
            status: string;
        };
        /**
         * PipelineReport
         * @description Bambuddy's report for one pipeline, passed through as it came.
         */
        PipelineReport: {
            /** Pipeline Id */
            pipeline_id: number;
            report: components["schemas"]["EligibilityReport"];
        };
        /** PipelineRun */
        PipelineRun: {
            /**
             * Copies
             * @default 1
             */
            copies: number;
            /**
             * Copies Cancelled
             * @default 0
             */
            copies_cancelled: number;
            /**
             * Copies Completed
             * @default 0
             */
            copies_completed: number;
            /**
             * Copies Failed
             * @default 0
             */
            copies_failed: number;
            /**
             * Copies In Progress
             * @default 0
             */
            copies_in_progress: number;
            /**
             * Eligibility Overridden
             * @default false
             */
            eligibility_overridden: boolean;
            /** Error Message */
            error_message?: string | null;
            /** Fanout Strategy */
            fanout_strategy?: ("max_parallel" | "fill_one_first" | "round_robin") | null;
            /** Id */
            id: number;
            /** Jobs */
            jobs?: components["schemas"]["PipelineJob"][];
            /** Pipeline Id */
            pipeline_id?: number | null;
            /** Pipeline Name */
            pipeline_name?: string | null;
            /** Slice Job Id */
            slice_job_id?: number | null;
            /** Sliced Library File Id */
            sliced_library_file_id?: number | null;
            /** Source Archive Id */
            source_archive_id?: number | null;
            /** Source Filename */
            source_filename?: string | null;
            /** Source Library File Id */
            source_library_file_id?: number | null;
            /** Status */
            status: string;
            /** Target Kind */
            target_kind?: ("specific_printer" | "printer_class") | null;
            /** Target Model Class */
            target_model_class?: string | null;
            /** Target Printer Id */
            target_printer_id?: number | null;
        };
        /**
         * PipelineView
         * @description A pipeline as the picker shows it: Bambuddy's row plus resolved preset names and
         *     the printers its target comes out as.
         */
        PipelineView: {
            /** Bed Type */
            bed_type?: string | null;
            /** Description */
            description?: string | null;
            /**
             * Fanout Strategy
             * @enum {string}
             */
            fanout_strategy: "max_parallel" | "fill_one_first" | "round_robin";
            /** Filament Preset Names */
            filament_preset_names?: (string | null)[];
            /** Filament Presets */
            filament_presets?: components["schemas"]["PresetRef"][];
            /** Id */
            id: number;
            /** Name */
            name: string;
            /** Printer Ids */
            printer_ids?: number[];
            printer_preset?: components["schemas"]["PresetRef"] | null;
            /** Printer Preset Name */
            printer_preset_name?: string | null;
            process_preset?: components["schemas"]["PresetRef"] | null;
            /** Process Preset Name */
            process_preset_name?: string | null;
            /**
             * Target Kind
             * @enum {string}
             */
            target_kind: "specific_printer" | "printer_class";
            /** Target Model Class */
            target_model_class?: string | null;
            /** Target Printer Id */
            target_printer_id?: number | null;
            /** Target Printer Name */
            target_printer_name?: string | null;
        };
        /**
         * PresetChoice
         * @description One row of the "New pipeline" form's pickers.
         *
         *     ``compatible_printers`` is normalised to a list here: ``/slicer/presets`` returns
         *     one, while ``/local-presets/`` stores the same thing as a JSON-encoded *string*.
         *     An empty list means the preset declares no restriction, not that it fits nothing.
         */
        PresetChoice: {
            /** Compatible Printers */
            compatible_printers?: string[];
            /** Filament Colour */
            filament_colour?: string | null;
            /** Filament Type */
            filament_type?: string | null;
            /** Name */
            name: string;
            ref: components["schemas"]["PresetRef"];
        };
        /**
         * PresetOptions
         * @description Printer presets and bed types always; process and filament only once a printer
         *     preset is named, because unfiltered those two tiers are thousands of rows.
         */
        PresetOptions: {
            /** Bed Types */
            bed_types?: string[];
            /** Filament */
            filament?: components["schemas"]["PresetChoice"][];
            /** Printer */
            printer?: components["schemas"]["PresetChoice"][];
            printer_preset?: components["schemas"]["PresetRef"] | null;
            /** Process */
            process?: components["schemas"]["PresetChoice"][];
        };
        /**
         * PresetRef
         * @description A slicer preset, identified by tier and id (``{"source":"cloud","id":"GM041"}``).
         */
        PresetRef: {
            /** Id */
            id: string;
            /**
             * Source
             * @enum {string}
             */
            source: "orca_cloud" | "cloud" | "local" | "standard";
        };
        /**
         * PrintRunRequest
         * @description ``pipeline_id`` omitted means "whatever this model defaults to".
         *
         *     ``force`` is the caller's explicit override of a blocking eligibility issue; the UI
         *     only offers it once the issues have been shown.
         */
        PrintRunRequest: {
            /**
             * Copies
             * @default 1
             */
            copies: number;
            /**
             * Force
             * @default false
             */
            force: boolean;
            /** Pipeline Id */
            pipeline_id?: number | null;
        };
        /** PrintRunResult */
        PrintRunResult: {
            /** Bambuddy Url */
            bambuddy_url: string;
            /** Library File Id */
            library_file_id: number;
            /** Pipeline Id */
            pipeline_id: number;
            run: components["schemas"]["PipelineRun"];
        };
        /**
         * Printer
         * @description ``GET /api/v1/printers/`` and ``GET /api/v1/printers/{id}`` — the same shape.
         *
         *     ``access_code`` is deliberately absent: Bambuddy withholds it from API-keyed
         *     callers, so a model that carried it would be null in production and populated
         *     only when auth is disabled.
         */
        Printer: {
            /** Id */
            id: number;
            /**
             * Is Active
             * @default true
             */
            is_active: boolean;
            /** Model */
            model?: string | null;
            /** Name */
            name: string;
            /** Nozzle Count */
            nozzle_count?: number | null;
        };
        /** RenderAccepted */
        RenderAccepted: {
            /** Job Id */
            job_id: string;
            /** Status Url */
            status_url: string;
        };
        /** RenderRequest */
        RenderRequest: {
            /** Params */
            params?: {
                [key: string]: boolean | number | string;
            };
        };
        /** SendRequest */
        SendRequest: {
            /**
             * Copies
             * @default 1
             */
            copies: number;
            /**
             * Mode
             * @default library
             * @enum {string}
             */
            mode: "library" | "queue";
        };
        /** SendResult */
        SendResult: {
            /** Bambuddy Url */
            bambuddy_url?: string | null;
            /** Filename */
            filename: string;
            /** Library File Id */
            library_file_id: number;
            /**
             * Mode
             * @enum {string}
             */
            mode: "library" | "queue";
            /** Pipeline Run Id */
            pipeline_run_id?: number | null;
            /** Queue Item Id */
            queue_item_id?: number | null;
        };
        /**
         * SettingsPatch
         * @description An omitted field is left alone; an explicit ``null`` clears it.
         */
        SettingsPatch: {
            /** Bambuddy Api Key */
            bambuddy_api_key?: string | null;
            /** Bambuddy Url */
            bambuddy_url?: string | null;
            /** Bed Type */
            bed_type?: string | null;
            /** Filament Presets */
            filament_presets?: components["schemas"]["PresetRef"][] | null;
            /** Library Folder Id */
            library_folder_id?: number | null;
            /** Pipeline Id */
            pipeline_id?: number | null;
            /** Printer Id */
            printer_id?: number | null;
            printer_preset?: components["schemas"]["PresetRef"] | null;
            process_preset?: components["schemas"]["PresetRef"] | null;
            /** Public Url */
            public_url?: string | null;
        };
        /**
         * SettingsView
         * @description What the browser may see. The API key itself never appears here.
         */
        SettingsView: {
            /** Bambuddy Url */
            bambuddy_url?: string | null;
            /** Bed Type */
            bed_type?: string | null;
            /** Filament Presets */
            filament_presets?: components["schemas"]["PresetRef"][];
            /**
             * Has Api Key
             * @default false
             */
            has_api_key: boolean;
            /** Library Folder Id */
            library_folder_id?: number | null;
            /** Pipeline Id */
            pipeline_id?: number | null;
            /** Printer Id */
            printer_id?: number | null;
            printer_preset?: components["schemas"]["PresetRef"] | null;
            process_preset?: components["schemas"]["PresetRef"] | null;
            /** Public Url */
            public_url?: string | null;
        };
        /**
         * SidebarLink
         * @description The External Link ScadBuddy registers, plus where Bambuddy renders it.
         */
        SidebarLink: {
            /** Created */
            created: boolean;
            /** Embed Path */
            embed_path: string;
            /** Icon */
            icon: string;
            /** Id */
            id: number;
            /** Name */
            name: string;
            /** Open In New Tab */
            open_in_new_tab: boolean;
            /** Url */
            url: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    get_fonts_api_v1_fonts_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FontFamily"][];
                };
            };
        };
    };
    get_catalogue_api_v1_fonts_catalogue_get: {
        parameters: {
            query?: {
                q?: string;
                category?: string;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FontCatalogueView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    install_font_api_v1_fonts_install_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["InstallRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InstalledFamily"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_job_api_v1_jobs__job_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobStatus"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_job_preview_api_v1_jobs__job_id__preview_glb_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "model/gltf-binary": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_models_api_v1_models_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ModelRecord"][];
                };
            };
        };
    };
    create_model_api_v1_models_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_create_model_api_v1_models_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ModelRecord"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_model_api_v1_models__slug__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ModelRecord"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_model_api_v1_models__slug__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    patch_model_api_v1_models__slug__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ModelPatch"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ModelRecord"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_outputs_api_v1_models__slug__outputs_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OutputDetail"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_output_api_v1_models__slug__outputs_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateOutputRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OutputDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    render_model_api_v1_models__slug__render_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RenderRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RenderAccepted"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_schema_api_v1_models__slug__schema_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CustomizerSchema"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_source_api_v1_models__slug__source_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/plain": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_thumbnail_api_v1_models__slug__thumbnail_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "image/png": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_output_api_v1_outputs__output_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                output_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OutputDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_output_api_v1_outputs__output_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                output_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    download_output_api_v1_outputs__output_id__model_3mf_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                output_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "model/3mf": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    send_output_to_bambuddy_api_v1_outputs__output_id__send_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                output_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SendRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SendResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_output_thumbnail_api_v1_outputs__output_id__thumbnail_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                output_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "image/png": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    put_output_thumbnail_api_v1_outputs__output_id__thumbnail_put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                output_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_put_output_thumbnail_api_v1_outputs__output_id__thumbnail_put"];
            };
        };
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    put_model_pipeline_api_v1_print_models__slug__pipeline_put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PipelineDefaultPatch"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PipelineDefault"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_model_pipelines_api_v1_print_models__slug__pipelines_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PipelineChoices"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    post_eligibility_api_v1_print_outputs__output_id__eligibility_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                output_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EligibilityCheck"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EligibilityOverview"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    post_run_api_v1_print_outputs__output_id__run_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                output_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PrintRunRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PrintRunResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    post_pipeline_api_v1_print_pipelines_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PipelineCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PipelineView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_presets_api_v1_print_presets_get: {
        parameters: {
            query?: {
                printer_preset_source?: ("orca_cloud" | "cloud" | "local" | "standard") | null;
                printer_preset_id?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PresetOptions"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_settings_api_v1_settings_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SettingsView"];
                };
            };
        };
    };
    put_settings_api_v1_settings_put: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SettingsPatch"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SettingsView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    post_register_sidebar_api_v1_settings_register_sidebar_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SidebarLink"];
                };
            };
        };
    };
    get_targets_api_v1_settings_targets_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BambuddyTargets"];
                };
            };
        };
    };
    test_settings_api_v1_settings_test_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConnectionTest"];
                };
            };
        };
    };
    healthz_healthz_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Health"];
                };
            };
        };
    };
}
