"""Where downloaded fonts live, and how OpenSCAD is told to look there.

OpenSCAD's ``text()`` resolves a family through fontconfig, which by default reads
only the system config — so a TTF dropped on the data volume is invisible to it no
matter where it lands. The fix is a second fontconfig config file that includes the
system one and adds the data directory, pointed at by ``FONTCONFIG_FILE`` in the
environment of every process that has to see those fonts: ``fc-list``, ``fc-cache``
and ``openscad`` itself.

The cache directory is declared **before** the system include on purpose. fontconfig
appends cache directories in document order and writes to the first one it can, and
the container's system cache is baked at build time and owned by root; without this
line ``fc-cache`` as uid 10001 falls back to ``$HOME/.cache`` and every render warns.

Those processes get an explicit, minimal environment rather than a copy of the
backend's (#281). ``openscad`` runs whatever a template says, and ``import()`` /
``surface()`` read any path they are handed — ``/proc/self/environ`` included — so
every variable the backend holds (a Bambuddy API key, a database URL) would be one
string parameter away from a render log. Only what the binaries actually read
passes through: the executable search path, the home and XDG directories, locale,
the temp dir and fontconfig's own variables.
"""

from __future__ import annotations

import os
from collections.abc import Mapping
from pathlib import Path

FONTS_DIR_NAME = "fonts"
CONF_NAME = "fonts.conf"
CACHE_DIR_NAME = ".cache"
SYSTEM_CONF = "/etc/fonts/fonts.conf"

_CONF_TEMPLATE = """\
<?xml version="1.0"?>
<!DOCTYPE fontconfig SYSTEM "urn:fontconfig:fonts.dtd">
<!-- Generated by ScadBuddy. Edits are overwritten on startup. -->
<fontconfig>
  <cachedir>{cache_dir}</cachedir>
  <dir>{fonts_dir}</dir>
  <include ignore_missing="yes">{system_conf}</include>
</fontconfig>
"""


def fonts_dir(data_dir: Path) -> Path:
    return data_dir / FONTS_DIR_NAME


def conf_path(data_dir: Path) -> Path:
    return fonts_dir(data_dir) / CONF_NAME


def cache_dir(data_dir: Path) -> Path:
    return fonts_dir(data_dir) / CACHE_DIR_NAME


def write_conf(data_dir: Path, *, system_conf: str = SYSTEM_CONF) -> Path:
    """Create the fonts directory, its cache directory and the config that joins them."""
    target = conf_path(data_dir)
    target.parent.mkdir(parents=True, exist_ok=True)
    cache_dir(data_dir).mkdir(parents=True, exist_ok=True)
    target.write_text(
        _CONF_TEMPLATE.format(
            cache_dir=cache_dir(data_dir),
            fonts_dir=fonts_dir(data_dir),
            system_conf=system_conf,
        ),
        encoding="utf-8",
    )
    return target


#: Parent variables a child process may inherit, by exact name. Anything else —
#: including every ``SCADBUDDY_*`` setting — is dropped.
PASSTHROUGH: frozenset[str] = frozenset(
    {
        "PATH",
        "HOME",
        "TMPDIR",
        "TZ",
        "LANG",
        "LANGUAGE",
        "FONTCONFIG_FILE",
        "FONTCONFIG_PATH",
        "XDG_CACHE_HOME",
        "XDG_CONFIG_HOME",
        "XDG_DATA_HOME",
        "XDG_STATE_HOME",
        "XDG_DATA_DIRS",
        "XDG_CONFIG_DIRS",
        "XDG_RUNTIME_DIR",
    }
)
#: ...and by prefix: ``LC_ALL``, ``LC_CTYPE`` and the rest of the locale family.
PASSTHROUGH_PREFIXES: tuple[str, ...] = ("LC_",)


def minimal_env(base: Mapping[str, str]) -> dict[str, str]:
    """The part of ``base`` a font-reading child process needs, and nothing else."""
    return {
        name: value
        for name, value in base.items()
        if name in PASSTHROUGH or name.startswith(PASSTHROUGH_PREFIXES)
    }


def env_for(data_dir: Path, base: Mapping[str, str] | None = None) -> dict[str, str]:
    """:func:`minimal_env` of ``base`` (the process environment by default), plus
    ``FONTCONFIG_FILE`` once the data volume's config exists.

    Falling through rather than pointing at a missing file matters: fontconfig treats
    an unreadable ``FONTCONFIG_FILE`` as a fatal config error and every ``fc-*`` call
    and every render would fail, instead of merely not seeing the downloaded fonts.
    """
    env = minimal_env(os.environ if base is None else base)
    target = conf_path(data_dir)
    if target.is_file():
        env["FONTCONFIG_FILE"] = str(target)
    return env
