"""Where downloaded fonts live, and how OpenSCAD is told to look there.

OpenSCAD's ``text()`` resolves a family through fontconfig, which by default reads
only the system config — so a TTF dropped on the data volume is invisible to it no
matter where it lands. The fix is a second fontconfig config file that includes the
system one and adds the data directory, pointed at by ``FONTCONFIG_FILE`` in the
environment of every process that has to see those fonts: ``fc-list``, ``fc-cache``
and ``openscad`` itself.

The cache directory is declared **before** the system include on purpose. fontconfig
appends cache directories in document order and writes to the first one it can, and
the container's system cache is baked at build time and owned by root; without this
line ``fc-cache`` as uid 10001 falls back to ``$HOME/.cache`` and every render warns.
"""

from __future__ import annotations

import os
from collections.abc import Mapping
from pathlib import Path

FONTS_DIR_NAME = "fonts"
CONF_NAME = "fonts.conf"
CACHE_DIR_NAME = ".cache"
SYSTEM_CONF = "/etc/fonts/fonts.conf"

_CONF_TEMPLATE = """\
<?xml version="1.0"?>
<!DOCTYPE fontconfig SYSTEM "urn:fontconfig:fonts.dtd">
<!-- Generated by ScadBuddy. Edits are overwritten on startup. -->
<fontconfig>
  <cachedir>{cache_dir}</cachedir>
  <dir>{fonts_dir}</dir>
  <include ignore_missing="yes">{system_conf}</include>
</fontconfig>
"""


def fonts_dir(data_dir: Path) -> Path:
    return data_dir / FONTS_DIR_NAME


def conf_path(data_dir: Path) -> Path:
    return fonts_dir(data_dir) / CONF_NAME


def cache_dir(data_dir: Path) -> Path:
    return fonts_dir(data_dir) / CACHE_DIR_NAME


def write_conf(data_dir: Path, *, system_conf: str = SYSTEM_CONF) -> Path:
    """Create the fonts directory, its cache directory and the config that joins them."""
    target = conf_path(data_dir)
    target.parent.mkdir(parents=True, exist_ok=True)
    cache_dir(data_dir).mkdir(parents=True, exist_ok=True)
    target.write_text(
        _CONF_TEMPLATE.format(
            cache_dir=cache_dir(data_dir),
            fonts_dir=fonts_dir(data_dir),
            system_conf=system_conf,
        ),
        encoding="utf-8",
    )
    return target


def env_for(data_dir: Path, base: Mapping[str, str] | None = None) -> dict[str, str]:
    """``base`` plus ``FONTCONFIG_FILE``, or ``base`` unchanged when no config exists.

    Falling through rather than pointing at a missing file matters: fontconfig treats
    an unreadable ``FONTCONFIG_FILE`` as a fatal config error and every ``fc-*`` call
    and every render would fail, instead of merely not seeing the downloaded fonts.
    """
    env = dict(os.environ if base is None else base)
    target = conf_path(data_dir)
    if target.is_file():
        env["FONTCONFIG_FILE"] = str(target)
    return env
